name: "Nitro OpenAPI Upload"
description: "Uploads OpenAPI documents to the Nitro registry"
author: "ChilliCream"
branding:
  icon: "upload-cloud"
  color: "green"

inputs:
  tag:
    description: "The tag of the OpenAPI collection version"
    required: true
  openapi-collection-id:
    description: "The ID of the OpenAPI collection"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
    secret: true
  patterns:
    description: "Glob patterns for selecting OpenAPI document files"
    required: true
  cloud-url:
    description: "The URL of the Nitro registry"
    required: false
  job-id:
    description: "The ID of the current job"
    required: false
    default: ${{ job.check_run_id }}

runs:
  using: "node20"
  main: "dist/index.js"
